### PR TITLE
Add Ubuntu 16.04, Ubuntu 18.04, and CentOS 7 support

### PR DESCRIPTION
**Pull request by jeffbyrnes**
@hyeomans, I’m taking what you provided in #4 and refactoring it to preserve some of the original thinking behind how I designed this cookbook originally.

I’m going to add tests to this, and probably refactor some more. Seeing as 14.04 is supported until 2019, I’m also going to try & preserve support for it, too.

### CODE REVIEW

**Comment by hyeomans** [comment]
Great! Thanks for the support @jeffbyrnes

**Comment by jeffbyrnes** [comment]
@hyeomans I saw you closed #4, sorry I never got this the attention I promised. I’m not sure I will, do you still need this?

**Comment by hyeomans** [comment]
hey @jeffbyrnes, don't worry about it, I'm not using it anymore.

**Comment by jeffbyrnes** [comment]
Ok, thanks @hyeomans. Sorry if my lack of action caused you any issues!

**Comment by jeffbyrnes** [comment]
Closing in favor of #6. I’ll see about adding CentOS support back as part of a later effort, but #6 provides stronger Ubuntu support while decreasing the maintenance overhead of this cookbook.

**Pull request closed without merging**
